#!/bin/sh

echo "RUN: at `date` by `whoami` act $ACTION $1 DEVPATH $DEVPATH DEVNAME $DEVNAME"
echo "Re-configuring keyboard!"

export DISPLAY=:0
xset r rate 220 30
xmodmap /home/matteo/.Xmodmap

echo "Exiting"
