#!/usr/bin/env sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FILESYSTEM=$(df -h $DISK | tail -1 | awk '{print $1}')
SIZE=$(df -h $DISK | tail -1 | awk '{print $2}')
USED=$(df -h $DISK | tail -1 | awk '{print $3}')
USE_PERCENT=$(df -h $DISK | tail -1 | awk '{print $5}' | sed 's/%//')

printf "%s  %s / %s  %s%%\n" "$FILESYSTEM" "$USED" "$SIZE"  "$USE_PERCENT"
printf "%s  %s%%\n" "$FILESYSTEM" "$USE_PERCENT"
if [[ $USE_PERCENT -gt 90 ]]
then
    printf "#E68183\n"
elif [[ $USE_PERCENT -gt 80 ]]
then
    printf "#D9BB80\n"
else
    printf ""
fi
