#!/bin/env bash
# Copyright (C) 2022 Matteo Gätzner <m.gaetzner@gmx.de>  

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DISK=/dev/nvme0n1p3
LOGFILE="$HOME/.config/i3blocks/backup/backup.space.info"

if ! [[ -f $LOGFILE ]]; then
  exit 0
fi

FILESYSTEM=$(cat $LOGFILE | awk '{print $1}')
SIZE=$(cat $LOGFILE | awk '{print $2}')
SIZE=$(numfmt --to iec --format "%.1f" $(($SIZE * 1000)))
USED=$(cat $LOGFILE | awk '{print $3}')
USED=$(numfmt --to iec --format "%.1f" $(($USED * 1000)))
USE_PERCENT=$(cat $LOGFILE | awk '{print $5}' | sed 's/%//')

printf "%s  %s / %s  %s%%\n" "$FILESYSTEM" "$USED" "$SIZE"  "$USE_PERCENT"
printf "%s  %s%%\n" "$FILESYSTEM" "$USE_PERCENT"
if [[ $USE_PERCENT -gt 90 ]]
then
  printf "#E68183\n"
elif [[ $USE_PERCENT -gt 80 ]]
then
  printf "#D9BB80\n"
else
  printf ""
fi
